biblio/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from shelf.views import BookListView

# tu przenosimy/grupujemy pathy do pliku
# uls.py w katalogu aplikacji shelf
app_name = "shelf"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('shelf/', include('shelf.urls', namespace='shelf')),
    path('books/', BookListView.as_view()),
]

shelf/urls.py
from django.urls import path
from .views import AuthorListView, AuthorDetailView

urlpatterns = [

    path('autors',AuthorListView.as_view(), name='author-list'),
    path('autors/<pk>', AuthorDetailView.as_view(), name='author-detail'),


]

shelf/models.py
# from __future__ import unicode_literals, absolute_import
from django.db import models
from django.contrib.auth.models import User

# ORM - Object Relations Mapper - powala trzymać obiekty w bazie danych


class Publisher(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return "{first_name} {last_name}".format(first_name=self.first_name,
                                                 last_name=self.last_name)

class Book(models.Model):

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    isbn = models.CharField(max_length=20)

    def __str__(self):
        return self.title

shelf/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Author # <=> from shelf.models import Author
from .models import Book # <=> from shelf.models import Book

# Create your views here.
# widoki .zapomocą jego będziemy wyciągać dane z bazy i wrzucać do szablonu (templates)

class AuthorListView(ListView):
    model = Author


class BookListView(ListView):
    model = Book

class AuthorDetailView(DetailView):
    model = Author

shelf/templates/shelf/author_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AuthorDetail</title>
</head>
<body>
{% extends 'base.html' %}

{% block 'content' %}
<div><a href="{%url 'shelf:author-list'%}">Powrót do listy autorów</a> </div>
<ul>
    Profil autora: {{ object.last_name }}, {{ object.first_name }}
</ul>
{% endblock %}
</body>
</html>

shelf/templates/shelf/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>POdtytul AuthorList</title>
</head>
<body>

{% extends 'base.html' %}

{% block 'content' %}
<ul>
    {% for author in object_list %}
    <li><a href="{%url 'shelf:author-detail' author.id %}"> {{author.first_name}} {{author.last_name}}</a></li>
    {% endfor %}
</ul>
{% endblock %}

</body>
</html>

shelf/templates/shelf/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BooksList</title>
</head>
<body>
{% extends 'base.html' %}

{% block 'content' %}
<ul>
    {% for book in object_list %}
    <li>{{book.title}} {{book.author}}</li>
    {% endfor %}
</ul>
{% endblock %}

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>First Project Base</title>
</head>
<body>
    {% block 'content' %} {# całość nazywa się template TAG #}
    <h1>Bloczysko tu !</h1>
    {% endblock %}
</body>
</html>